In [2]:
#Arrays:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8]], dtype=np.uint8)
print(a.ndim, a.shape, a.dtype)

2 (2, 4) uint8


In [90]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=uint8)

In [3]:

b = np.ones((2,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
c = np.zeros((4,4))
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.concatenate([b,c])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
d = np.zeros_like(b)
d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
a

array([1, 2, 3, 4, 5, 6])

In [25]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
#ravel():
a = np.array([1,2,3,4,5,6])
a = a.reshape(2,-3)
a = a.ravel()
a

array([1, 2, 3, 4, 5, 6])

In [31]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
#a.T:
a = a.reshape(3, 2)
print(a)
a.T

[[1 2]
 [3 4]
 [5 6]]


array([[1, 3, 5],
       [2, 4, 6]])

In [1]:
#Shape and dtype function:
import numpy as np
A = [1,2,3,4]
data = np.array(A)

print(data.shape)
print(data.dtype)

(4,)
int32


In [2]:
#Making a circle using circles with turtle library:
import turtle

x=turtle.Turtle()

def circle(angle):
    x.circle(50)
    x.right(angle+5)
for i in range(50):
    circle(30)

Terminator: 