In [34]:
#First case (A 2d(5x4) and a 1d(4x1) array broadcasting):
A = [ [1, 3, 5, 7], [8, 5, 6, 2], [7, 1, 6, 4], [3, 5, 7, 9], [12, 4, 1, 2] ]
import numpy as np
A = np.array(A)
print("The shape of A: ", A.shape)

B = [3]
B = np.array(B)
print("The shape of B: ", B.shape)

C = A*B
print(C)
print("The final shape after broadcasting: ", C.shape)

The shape of A:  (5, 4)
The shape of B:  (1,)
[[ 3  9 15 21]
 [24 15 18  6]
 [21  3 18 12]
 [ 9 15 21 27]
 [36 12  3  6]]
The final shape after broadcasting:  (5, 4)


In [35]:
#Second case(A 2d(5x4) and a 1d(4x1) array broadcasting):
A = [ [1, 3, 5, 7], [8, 5, 6, 2], [7, 1, 6, 4], [3, 5, 7, 9], [12, 4, 1, 2] ]
import numpy as np
A = np.array(A)
print("The shape of A: ", A.shape)

B = [3, 4, 5, 6]
B = np.array(B)
print("The shape of B: ", B.shape)

C = A*B
print(C)
print("The final shape after broadcasting: ", C.shape)

The shape of A:  (5, 4)
The shape of B:  (4,)
[[ 3 12 25 42]
 [24 20 30 12]
 [21  4 30 24]
 [ 9 20 35 54]
 [36 16  5 12]]
The final shape after broadcasting:  (5, 4)


In [37]:
#Third case(A 3d(5x3x5) and a 3d(5x1x5) array broadcasting):
A = [ [[1, 3, 5, 7, 8], [8, 5, 6, 2, 1], [7, 1, 6, 4, 6]],
     [[3, 5, 7, 9, 2], [12, 4, 1, 2, 8], [6, 7, 8, 9, 1]],
    [[3, 5, 7, 9, 1], [12, 4, 1, 2, 4], [6, 7, 8, 9, 3]],
    [[3, 5, 7, 9, 4], [12, 4, 1, 2, 7], [6, 7, 8, 9, 5]],
    [[3, 5, 7, 9, 7], [12, 4, 1, 2, 5], [6, 7, 8, 9, 4]],]
import numpy as np
A = np.array(A)
print("The shape of A: ", A.shape)

B = [ [[1, 3, 5, 7, 8]],
     [[3, 5, 7, 9, 2]],
    [[3, 5, 7, 9, 1]],
    [[3, 5, 7, 9, 4]],
    [[3, 5, 7, 9, 7]]]
B = np.array(B)
print("The shape of B: ", B.shape)

C = A*B
print(C)
print("The final shape after broadcasting: ", C.shape)

The shape of A:  (5, 3, 5)
The shape of B:  (5, 1, 5)
[[[ 1  9 25 49 64]
  [ 8 15 30 14  8]
  [ 7  3 30 28 48]]

 [[ 9 25 49 81  4]
  [36 20  7 18 16]
  [18 35 56 81  2]]

 [[ 9 25 49 81  1]
  [36 20  7 18  4]
  [18 35 56 81  3]]

 [[ 9 25 49 81 16]
  [36 20  7 18 28]
  [18 35 56 81 20]]

 [[ 9 25 49 81 49]
  [36 20  7 18 35]
  [18 35 56 81 28]]]
The final shape after broadcasting:  (5, 3, 5)


In [32]:
#Fourth case(A 3d(5x3x5) and a 2d(3x5) array broadcasting):
A = [ [[1, 3, 5, 7, 8], [8, 5, 6, 2, 1], [7, 1, 6, 4, 6]],
     [[3, 5, 7, 9, 2], [12, 4, 1, 2, 8], [6, 7, 8, 9, 1]],
    [[3, 5, 7, 9, 1], [12, 4, 1, 2, 4], [6, 7, 8, 9, 3]],
    [[3, 5, 7, 9, 4], [12, 4, 1, 2, 7], [6, 7, 8, 9, 5]],
    [[3, 5, 7, 9, 7], [12, 4, 1, 2, 5], [6, 7, 8, 9, 4]],]
import numpy as np
A = np.array(A)
print("The shape of A: ",A.shape)

B = [[1, 3, 5, 7, 8], [3, 5, 7, 9, 2], [3, 5, 7, 9, 1]]
B = np.array(B)
print("The shape of B: ", B.shape)

C = A*B
print(C)
print("The final shape after broadcasting: ", C.shape)

The shape of A:  (5, 3, 5)
The shape of B:  (3, 5)
[[[ 1  9 25 49 64]
  [24 25 42 18  2]
  [21  5 42 36  6]]

 [[ 3 15 35 63 16]
  [36 20  7 18 16]
  [18 35 56 81  1]]

 [[ 3 15 35 63  8]
  [36 20  7 18  8]
  [18 35 56 81  3]]

 [[ 3 15 35 63 32]
  [36 20  7 18 14]
  [18 35 56 81  5]]

 [[ 3 15 35 63 56]
  [36 20  7 18 10]
  [18 35 56 81  4]]]
The final shape after broadcasting:  (5, 3, 5)


In [33]:
#Fifth case(A 3d(5x3x5) and a 2d(3x1) array broadcasting):
A = [ [[1, 3, 5, 7, 8], [8, 5, 6, 2, 1], [7, 1, 6, 4, 6]],
     [[3, 5, 7, 9, 2], [12, 4, 1, 2, 8], [6, 7, 8, 9, 1]],
    [[3, 5, 7, 9, 1], [12, 4, 1, 2, 4], [6, 7, 8, 9, 3]],
    [[3, 5, 7, 9, 4], [12, 4, 1, 2, 7], [6, 7, 8, 9, 5]],
    [[3, 5, 7, 9, 7], [12, 4, 1, 2, 5], [6, 7, 8, 9, 4]],]
import numpy as np
A = np.array(A)
print("The shape of A: ",A.shape)

B = [[1], [2], [3]]
B = np.array(B)
print("The shape of B: ", B.shape)

C = A*B
print(C)
print("The final shape after broadcasting: ", C.shape)

The shape of A:  (5, 3, 5)
The shape of B:  (3, 1)
[[[ 1  3  5  7  8]
  [16 10 12  4  2]
  [21  3 18 12 18]]

 [[ 3  5  7  9  2]
  [24  8  2  4 16]
  [18 21 24 27  3]]

 [[ 3  5  7  9  1]
  [24  8  2  4  8]
  [18 21 24 27  9]]

 [[ 3  5  7  9  4]
  [24  8  2  4 14]
  [18 21 24 27 15]]

 [[ 3  5  7  9  7]
  [24  8  2  4 10]
  [18 21 24 27 12]]]
The final shape after broadcasting:  (5, 3, 5)


In [39]:
#Failure cases(try 1: 2d and 2d array):
A = [ [1, 3, 5, 7], [8, 5, 6, 2], [7, 1, 6, 4], [3, 5, 7, 9], [12, 4, 1, 2] ]
import numpy as np
A = np.array(A)
print("The shape of A: ", A.shape)

B = [3, 4, 5]
B = np.array(B)
print("The shape of B: ", B.shape)

C = A*B
print(C)
print("The final shape after broadcasting: ", C.shape)

The shape of A:  (5, 4)
The shape of B:  (3,)


ValueError: operands could not be broadcast together with shapes (5,4) (3,) 

In [42]:
#Fifth case(A 3d(5x3x5) and a 2d(3x1) array broadcasting):
A = [ [[1, 3, 5, 7, 8], [8, 5, 6, 2, 1], [7, 1, 6, 4, 6]],
     [[3, 5, 7, 9, 2], [12, 4, 1, 2, 8], [6, 7, 8, 9, 1]],
    [[3, 5, 7, 9, 1], [12, 4, 1, 2, 4], [6, 7, 8, 9, 3]],
    [[3, 5, 7, 9, 4], [12, 4, 1, 2, 7], [6, 7, 8, 9, 5]],
    [[3, 5, 7, 9, 7], [12, 4, 1, 2, 5], [6, 7, 8, 9, 4]],]
import numpy as np
A = np.array(A)
print("The shape of A: ",A.shape)

B = [[1], [2]]
B = np.array(B)
print("The shape of B: ", B.shape)

C = A*B.T
print(C)
print("The final shape after broadcasting: ", C.shape)

The shape of A:  (5, 3, 5)
The shape of B:  (2, 1)


ValueError: operands could not be broadcast together with shapes (5,3,5) (1,2) 